<?php

/**
 * ConfigurationsUsageEnum
 *
 * PHP version 8.1
 *
 * @package  eBay\Sell\Feed
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Feed API
 *
 * <p>The <strong>Sell Feed API</strong> lets sellers upload input files, download reports and files including their status, filter reports using URI parameters, and retrieve customer service metrics task details.</p>
 *
 * The version of the OpenAPI document: v1.3.1
 * @generated Generated by: https://openapi-generator.tech
 * Generator version: 7.25.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace eBay\Sell\Feed\Model;

/**
 * ConfigurationsUsageEnum Class Doc Comment
 *
 * @description An enumerated type for the values that represent whether the configuration parameter specified is required. | - **OPTIONAL**: This value represents that the associated configuration parameter does not need to be specified. If a default value is provided, that value will be used unless overwritten. - **REQUIRED**: This value represents that the associated configuration parameter needs to be specified.
 * @package  eBay\Sell\Feed
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
enum ConfigurationsUsageEnum: string
{
    case OPTIONAL = 'OPTIONAL';

    case REQUIRED = 'REQUIRED';
}


