<?php

/**
 * CustomerServiceMetricTypeEnum
 *
 * PHP version 8.1
 *
 * @package  eBay\Sell\Feed
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Feed API
 *
 * <p>The <strong>Sell Feed API</strong> lets sellers upload input files, download reports and files including their status, filter reports using URI parameters, and retrieve customer service metrics task details.</p>
 *
 * The version of the OpenAPI document: v1.3.1
 * @generated Generated by: https://openapi-generator.tech
 * Generator version: 7.25.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace eBay\Sell\Feed\Model;

/**
 * CustomerServiceMetricTypeEnum Class Doc Comment
 *
 * @description This enumerated type lists the Customer Service Metric types that are available for Customer Service Metric reports generated with the Feed API. | - **ITEM_NOT_AS_DESCRIBED**: The metric rating is based on Item not as described (SNAD) transactions. - **ITEM_NOT_RECEIVED**: The metric rating is based on Item not received (INR) transactions.
 * @package  eBay\Sell\Feed
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
enum CustomerServiceMetricTypeEnum: string
{
    case ITEM_NOT_AS_DESCRIBED = 'ITEM_NOT_AS_DESCRIBED';

    case ITEM_NOT_RECEIVED = 'ITEM_NOT_RECEIVED';
}


