<?php

/**
 * DayOfWeekEnum
 *
 * PHP version 8.1
 *
 * @package  eBay\Sell\Feed
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Feed API
 *
 * <p>The <strong>Sell Feed API</strong> lets sellers upload input files, download reports and files including their status, filter reports using URI parameters, and retrieve customer service metrics task details.</p>
 *
 * The version of the OpenAPI document: v1.3.1
 * @generated Generated by: https://openapi-generator.tech
 * Generator version: 7.25.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace eBay\Sell\Feed\Model;

/**
 * DayOfWeekEnum Class Doc Comment
 *
 * @description An enumerated type defining the days of the week. | - **SUN**: Indicates Sunday - **MON**: Indicates Monday - **TUE**: Indicates Tuesday - **WED**: Indicates Wednesday - **THU**: Indicates Thursday - **FRI**: Indicates Friday - **SAT**: Indicates Saturday
 * @package  eBay\Sell\Feed
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
enum DayOfWeekEnum: string
{
    case SUN = 'SUN';

    case MON = 'MON';

    case TUE = 'TUE';

    case WED = 'WED';

    case THU = 'THU';

    case FRI = 'FRI';

    case SAT = 'SAT';
}


