<?php

/**
 * ErrorDetail
 *
 * PHP version 8.1
 *
 * @package  eBay\Sell\Feed
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Feed API
 *
 * <p>The <strong>Sell Feed API</strong> lets sellers upload input files, download reports and files including their status, filter reports using URI parameters, and retrieve customer service metrics task details.</p>
 *
 * The version of the OpenAPI document: v1.3.1
 * @generated Generated by: https://openapi-generator.tech
 * Generator version: 7.25.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace eBay\Sell\Feed\Model;

use ArrayAccess;
use JsonSerializable;
use InvalidArgumentException;
use ReturnTypeWillChange;
use eBay\Sell\Feed\ObjectSerializer;

/**
 * ErrorDetail Class Doc Comment
 *
 * @description An instance of an error or warning as defined by the COS/ETS error handling standard.
 * @package  eBay\Sell\Feed
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements ArrayAccess<string, mixed>
 */
class ErrorDetail implements ModelInterface, ArrayAccess, JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static string $openAPIModelName = 'ErrorDetail';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var array<string, string>
     */
    protected static array $openAPITypes = [
        'error_id' => 'int',
        'domain' => 'string',
        'subdomain' => 'string',
        'category' => 'string',
        'message' => 'string',
        'long_message' => 'string',
        'input_ref_ids' => 'string[]',
        'output_ref_ids' => 'string[]',
        'parameters' => '\eBay\Sell\Feed\Model\ErrorParameter[]'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var array<string, string|null>
     */
    protected static array $openAPIFormats = [
        'error_id' => 'int64',
        'domain' => null,
        'subdomain' => null,
        'category' => null,
        'message' => null,
        'long_message' => null,
        'input_ref_ids' => null,
        'output_ref_ids' => null,
        'parameters' => null
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var array<string, bool>
     */
    protected static array $openAPINullables = [
        'error_id' => false,
        'domain' => false,
        'subdomain' => false,
        'category' => false,
        'message' => false,
        'long_message' => false,
        'input_ref_ids' => false,
        'output_ref_ids' => false,
        'parameters' => false
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var array<string, bool>
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * {@inheritdoc}
     */
    public static function openAPITypes(): array
    {
        return self::$openAPITypes;
    }

    /**
     * {@inheritdoc}
     */
    public static function openAPIFormats(): array
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array<string, bool>
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return array<string, bool>
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param array<string, bool> $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * {@inheritdoc}
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * {@inheritdoc}
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var array<string, string>
     */
    protected static array $attributeMap = [
        'error_id' => 'errorId',
        'domain' => 'domain',
        'subdomain' => 'subdomain',
        'category' => 'category',
        'message' => 'message',
        'long_message' => 'longMessage',
        'input_ref_ids' => 'inputRefIds',
        'output_ref_ids' => 'outputRefIds',
        'parameters' => 'parameters'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var array<string, string>
     */
    protected static array $setters = [
        'error_id' => 'setErrorId',
        'domain' => 'setDomain',
        'subdomain' => 'setSubdomain',
        'category' => 'setCategory',
        'message' => 'setMessage',
        'long_message' => 'setLongMessage',
        'input_ref_ids' => 'setInputRefIds',
        'output_ref_ids' => 'setOutputRefIds',
        'parameters' => 'setParameters'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var array<string, string>
     */
    protected static array $getters = [
        'error_id' => 'getErrorId',
        'domain' => 'getDomain',
        'subdomain' => 'getSubdomain',
        'category' => 'getCategory',
        'message' => 'getMessage',
        'long_message' => 'getLongMessage',
        'input_ref_ids' => 'getInputRefIds',
        'output_ref_ids' => 'getOutputRefIds',
        'parameters' => 'getParameters'
    ];

    /**
     * {@inheritdoc}
     */
    public static function attributeMap(): array
    {
        return self::$attributeMap;
    }

    /**
     * {@inheritdoc}
     */
    public static function setters(): array
    {
        return self::$setters;
    }

    /**
     * {@inheritdoc}
     */
    public static function getters(): array
    {
        return self::$getters;
    }

    /**
     * {@inheritdoc}
     */
    public function getModelName(): string
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var array
     */
    protected array $container = [];

    /**
     * Constructor
     *
     * @param array $data Associated array of property values initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('error_id', $data ?? [], null);
        $this->setIfExists('domain', $data ?? [], null);
        $this->setIfExists('subdomain', $data ?? [], null);
        $this->setIfExists('category', $data ?? [], null);
        $this->setIfExists('message', $data ?? [], null);
        $this->setIfExists('long_message', $data ?? [], null);
        $this->setIfExists('input_ref_ids', $data ?? [], null);
        $this->setIfExists('output_ref_ids', $data ?? [], null);
        $this->setIfExists('parameters', $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, mixed $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * {@inheritdoc}
     */
    public function listInvalidProperties(): array
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * {@inheritdoc}
     */
    public function valid(): bool
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets error_id
     *
     * @return int|null
     */
    public function getErrorId(): ?int
    {
        return $this->container['error_id'];
    }

    /**
     * Sets error_id
     *
     * @param int|null $error_id uniquely identifying the error within its Domain.
     *
     * @return $this
     */
    public function setErrorId(?int $error_id): static
    {
        if (is_null($error_id)) {
            throw new InvalidArgumentException('non-nullable error_id cannot be null');
        }
        $this->container['error_id'] = $error_id;

        return $this;
    }

    /**
     * Gets domain
     *
     * @return string|null
     */
    public function getDomain(): ?string
    {
        return $this->container['domain'];
    }

    /**
     * Sets domain
     *
     * @param string|null $domain The domain your service/application is in
     *
     * @return $this
     */
    public function setDomain(?string $domain): static
    {
        if (is_null($domain)) {
            throw new InvalidArgumentException('non-nullable domain cannot be null');
        }
        $this->container['domain'] = $domain;

        return $this;
    }

    /**
     * Gets subdomain
     *
     * @return string|null
     */
    public function getSubdomain(): ?string
    {
        return $this->container['subdomain'];
    }

    /**
     * Sets subdomain
     *
     * @param string|null $subdomain Name of the subsystem or subdivision of the domain
     *
     * @return $this
     */
    public function setSubdomain(?string $subdomain): static
    {
        if (is_null($subdomain)) {
            throw new InvalidArgumentException('non-nullable subdomain cannot be null');
        }
        $this->container['subdomain'] = $subdomain;

        return $this;
    }

    /**
     * Gets category
     *
     * @return string|null
     */
    public function getCategory(): ?string
    {
        return $this->container['category'];
    }

    /**
     * Sets category
     *
     * @param string|null $category The error's type, with allowed values APPLICATION, BUSINESS, or REQUEST
     *
     * @return $this
     */
    public function setCategory(?string $category): static
    {
        if (is_null($category)) {
            throw new InvalidArgumentException('non-nullable category cannot be null');
        }
        $this->container['category'] = $category;

        return $this;
    }

    /**
     * Gets message
     *
     * @return string|null
     */
    public function getMessage(): ?string
    {
        return $this->container['message'];
    }

    /**
     * Sets message
     *
     * @param string|null $message A device agnostic message that is end user and app developer friendly. It should explain what the error or warning is, and how it can be fixed (in a general sense). The value MUST be limited to 50 or fewer characters. If applicable, it must also be localized in the end user's requested locale. Refer to Section 6, Error Message Content and Localization.
     *
     * @return $this
     */
    public function setMessage(?string $message): static
    {
        if (is_null($message)) {
            throw new InvalidArgumentException('non-nullable message cannot be null');
        }
        $this->container['message'] = $message;

        return $this;
    }

    /**
     * Gets long_message
     *
     * @return string|null
     */
    public function getLongMessage(): ?string
    {
        return $this->container['long_message'];
    }

    /**
     * Sets long_message
     *
     * @param string|null $long_message An expanded version of message that SHOULD be limited to about 100-200 characters.
     *
     * @return $this
     */
    public function setLongMessage(?string $long_message): static
    {
        if (is_null($long_message)) {
            throw new InvalidArgumentException('non-nullable long_message cannot be null');
        }
        $this->container['long_message'] = $long_message;

        return $this;
    }

    /**
     * Gets input_ref_ids
     *
     * @return string[]|null
     */
    public function getInputRefIds(): ?array
    {
        return $this->container['input_ref_ids'];
    }

    /**
     * Sets input_ref_ids
     *
     * @param string[]|null $input_ref_ids Identifies specific request elements associated with the error, if any. inputRefId's response is format specific. For XML, use XPath notation. For JSON, use JSONPath notation.
     *
     * @return $this
     */
    public function setInputRefIds(?array $input_ref_ids): static
    {
        if (is_null($input_ref_ids)) {
            throw new InvalidArgumentException('non-nullable input_ref_ids cannot be null');
        }
        $this->container['input_ref_ids'] = $input_ref_ids;

        return $this;
    }

    /**
     * Gets output_ref_ids
     *
     * @return string[]|null
     */
    public function getOutputRefIds(): ?array
    {
        return $this->container['output_ref_ids'];
    }

    /**
     * Sets output_ref_ids
     *
     * @param string[]|null $output_ref_ids Identifies specific response elements associated with the error, if any. Path format is the same as inputRefId.
     *
     * @return $this
     */
    public function setOutputRefIds(?array $output_ref_ids): static
    {
        if (is_null($output_ref_ids)) {
            throw new InvalidArgumentException('non-nullable output_ref_ids cannot be null');
        }
        $this->container['output_ref_ids'] = $output_ref_ids;

        return $this;
    }

    /**
     * Gets parameters
     *
     * @return \eBay\Sell\Feed\Model\ErrorParameter[]|null
     */
    public function getParameters(): ?array
    {
        return $this->container['parameters'];
    }

    /**
     * Sets parameters
     *
     * @param \eBay\Sell\Feed\Model\ErrorParameter[]|null $parameters Used to specify information relevant to the end user/client.
     *
     * @return $this
     */
    public function setParameters(?array $parameters): static
    {
        if (is_null($parameters)) {
            throw new InvalidArgumentException('non-nullable parameters cannot be null');
        }
        $this->container['parameters'] = $parameters;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param int|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param int|string $offset Offset
     *
     * @return mixed|null
     */
    #[ReturnTypeWillChange]
    public function offsetGet(mixed $offset): mixed
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|string|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet(mixed $offset, mixed $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param int|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[ReturnTypeWillChange]
    public function jsonSerialize(): mixed
    {
        return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString(): string
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue(): string
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


