<?php

/**
 * FeedStatusEnum
 *
 * PHP version 8.1
 *
 * @package  eBay\Sell\Feed
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Feed API
 *
 * <p>The <strong>Sell Feed API</strong> lets sellers upload input files, download reports and files including their status, filter reports using URI parameters, and retrieve customer service metrics task details.</p>
 *
 * The version of the OpenAPI document: v1.3.1
 * @generated Generated by: https://openapi-generator.tech
 * Generator version: 7.25.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace eBay\Sell\Feed\Model;

/**
 * FeedStatusEnum Class Doc Comment
 *
 * @description An enumerated type for the values that represent the state of the task. | - **CREATED**: Indicates the task has been created. - **QUEUED**: Indicates the task has been added to the queue. - **IN_PROCESS**: Indicates the task is being processed. - **COMPLETED**: Indicates the task has finished being processed. - **COMPLETED_WITH_ERROR**: Indicates the task has completed but there are errors. If there are errors, they will be indicated in the report. - **FAILED**: Indicates the task has failed to complete. - **PARTIALLY_PROCESSED**: Indicates the task has failed to complete but was partially processed.
 * @package  eBay\Sell\Feed
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
enum FeedStatusEnum: string
{
    case CREATED = 'CREATED';

    case QUEUED = 'QUEUED';

    case IN_PROCESS = 'IN_PROCESS';

    case COMPLETED = 'COMPLETED';

    case COMPLETED_WITH_ERROR = 'COMPLETED_WITH_ERROR';

    case FAILED = 'FAILED';

    case PARTIALLY_PROCESSED = 'PARTIALLY_PROCESSED';
}


