<?php

/**
 * FrequencyEnum
 *
 * PHP version 8.1
 *
 * @package  eBay\Sell\Feed
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Feed API
 *
 * <p>The <strong>Sell Feed API</strong> lets sellers upload input files, download reports and files including their status, filter reports using URI parameters, and retrieve customer service metrics task details.</p>
 *
 * The version of the OpenAPI document: v1.3.1
 * @generated Generated by: https://openapi-generator.tech
 * Generator version: 7.25.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace eBay\Sell\Feed\Model;

/**
 * FrequencyEnum Class Doc Comment
 *
 * @description An enumerated type for the values that represent the frequency (specified by the template) for triggering the schedule. | - **HALF_HOUR**: Triggered every 30 minutes (every half hour) - **ONE_HOUR**: Triggered every 60 minutes (every hour) - **FOUR_HOURS**: Triggered every 240 minutes (every four hours) - **EIGHT_HOURS**: Triggered every 480 minutes (every eight hours) - **DAILY**: Triggered every 1440 minutes (every day) - **WEEKLY**: Triggered every 10080 minutes (every week) - **MONTHLY**: Triggered every month - **QUARTERLY**: Triggered every quarter (3 months)
 * @package  eBay\Sell\Feed
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
enum FrequencyEnum: string
{
    case HALF_HOUR = 'HALF_HOUR';

    case ONE_HOUR = 'ONE_HOUR';

    case FOUR_HOURS = 'FOUR_HOURS';

    case EIGHT_HOURS = 'EIGHT_HOURS';

    case DAILY = 'DAILY';

    case WEEKLY = 'WEEKLY';

    case MONTHLY = 'MONTHLY';

    case QUARTERLY = 'QUARTERLY';
}


