<?php

/**
 * ListingFormatEnum
 *
 * PHP version 8.1
 *
 * @package  eBay\Sell\Feed
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Feed API
 *
 * <p>The <strong>Sell Feed API</strong> lets sellers upload input files, download reports and files including their status, filter reports using URI parameters, and retrieve customer service metrics task details.</p>
 *
 * The version of the OpenAPI document: v1.3.1
 * @generated Generated by: https://openapi-generator.tech
 * Generator version: 7.25.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace eBay\Sell\Feed\Model;

/**
 * ListingFormatEnum Class Doc Comment
 *
 * @description An enumerated type that represents the listing format of an inventory item. | - **AUCTION**: This enumeration value indicates an AUCTION listing format. - **FIXED_PRICE**: This enumeration value indicates a FIXED_PRICE listing format.
 * @package  eBay\Sell\Feed
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
enum ListingFormatEnum: string
{
    case AUCTION = 'AUCTION';

    case FIXED_PRICE = 'FIXED_PRICE';
}


