<?php

/**
 * OrderStatusEnum
 *
 * PHP version 8.1
 *
 * @package  eBay\Sell\Feed
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Feed API
 *
 * <p>The <strong>Sell Feed API</strong> lets sellers upload input files, download reports and files including their status, filter reports using URI parameters, and retrieve customer service metrics task details.</p>
 *
 * The version of the OpenAPI document: v1.3.1
 * @generated Generated by: https://openapi-generator.tech
 * Generator version: 7.25.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace eBay\Sell\Feed\Model;

/**
 * OrderStatusEnum Class Doc Comment
 *
 * @description An enumerated type for the values that represent the state of the order. This is used by Large Merchant Services (LMS) sellers only. | - **ACTIVE**: Indicates the buyer has not paid for the order. - **COMPLETED**: Indicates the buyer has paid for the order and checkout is complete.
 * @package  eBay\Sell\Feed
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
enum OrderStatusEnum: string
{
    case ACTIVE = 'ACTIVE';

    case COMPLETED = 'COMPLETED';
}


