<?php

namespace eBay\Sell\Feed\Constants;

/**
 * https://developer.ebay.com/api-docs/sell/static/lms-migration/lms-to-feed-feedtype.html
 */
class FeedType
{
    const FX_FULFILLMENT = 'FX_FULFILLMENT';
    const FX_LISTING = 'FX_LISTING';
    const LMS_ACTIVE_INVENTORY_REPORT = 'LMS_ACTIVE_INVENTORY_REPORT';
    const LMS_ADD_FIXED_PRICE_ITEM = 'LMS_ADD_FIXED_PRICE_ITEM';
    const LMS_ADD_ITEM = 'LMS_ADD_ITEM';
    const LMS_END_FIXED_PRICE_ITEM = 'LMS_END_ FIXED_PRICE_ITEM';
    const LMS_END_ITEM = 'LMS_END_ITEM';
    const LMS_ORDER_ACK = 'LMS_ORDER_ACK';
    const LMS_ORDER_REPORT = 'LMS_ORDER_REPORT';
    const LMS_RELIST_FIXED_PRICE_ITEM = 'LMS_RELIST_ FIXED_PRICE_ITEM';
    const LMS_RELIST_ITEM = 'LMS_RELIST_ITEM';
    const LMS_REVISE_FIXED_PRICE_ITEM = 'LMS_REVISE_FIXED_PRICE_ITEM';
    const LMS_REVISE_INVENTORY_STATUS = 'LMS_REVISE_INVENTORY_STATUS';
    const LMS_REVISE_ITEM = 'LMS_REVISE_ITEM';
    const LMS_SET_SHIPMENT_TRACKING_INFO = 'LMS_SET_SHIPMENT_TRACKING_INFO';
    const LMS_VERIFY_ADD_ITEM = 'LMS_VERIFY_ADD_ITEM';
    const LMS_VERIFY_ADD_FIXED_PRICE_ITEM = 'LMS_VERIFY_ADD_FIXED_PRICE_ITEM';
}
