<?php
/**
 * FrequencyEnumTest
 *
 * PHP version 8.1
 *
 * @package  eBay\Sell\Feed
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Feed API
 *
 * <p>The <strong>Sell Feed API</strong> lets sellers upload input files, download reports and files including their status, filter reports using URI parameters, and retrieve customer service metrics task details.</p>
 *
 * The version of the OpenAPI document: v1.3.1
 * @generated Generated by: https://openapi-generator.tech
 * Generator version: 7.25.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace eBay\Sell\Feed\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * FrequencyEnumTest Class Doc Comment
 *
 * @description An enumerated type for the values that represent the frequency (specified by the template) for triggering the schedule. | - **HALF_HOUR**: Triggered every 30 minutes (every half hour) - **ONE_HOUR**: Triggered every 60 minutes (every hour) - **FOUR_HOURS**: Triggered every 240 minutes (every four hours) - **EIGHT_HOURS**: Triggered every 480 minutes (every eight hours) - **DAILY**: Triggered every 1440 minutes (every day) - **WEEKLY**: Triggered every 10080 minutes (every week) - **MONTHLY**: Triggered every month - **QUARTERLY**: Triggered every quarter (3 months)
 * @package     eBay\Sell\Feed
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class FrequencyEnumTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "FrequencyEnum"
     */
    public function testFrequencyEnum()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
