<?php
/**
 * ShippingRegionTypeEnumTest
 *
 * PHP version 8.1
 *
 * @package  eBay\Sell\Feed
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Feed API
 *
 * <p>The <strong>Sell Feed API</strong> lets sellers upload input files, download reports and files including their status, filter reports using URI parameters, and retrieve customer service metrics task details.</p>
 *
 * The version of the OpenAPI document: v1.3.1
 * @generated Generated by: https://openapi-generator.tech
 * Generator version: 7.25.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace eBay\Sell\Feed\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * ShippingRegionTypeEnumTest Class Doc Comment
 *
 * @description This enumerated type lists the types that are available for Shipping Regions. | - **DOMESTIC**: Listing and Item Shipped market places are the same. - **INTERNATIONAL_MATURED_REGION**: Items are shipped outside of the listing marketplace and shipped to one of the countries described in the policy page. https://www.ebay.com/help/selling/selling/monitor-service-metrics?id&#x3D;4785#section4 - **INTERNATIONAL_EMERGING_REGION**: Items are shipped outside of the listing marketplace and shipped to countries which are not part of the International Mature region. https://www.ebay.com/help/selling/selling/monitor-service-metrics?id&#x3D;4785#section4
 * @package     eBay\Sell\Feed
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class ShippingRegionTypeEnumTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "ShippingRegionTypeEnum"
     */
    public function testShippingRegionTypeEnum()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
