<?php
/**
 * StatusReasonEnumTest
 *
 * PHP version 8.1
 *
 * @package  eBay\Sell\Feed
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Feed API
 *
 * <p>The <strong>Sell Feed API</strong> lets sellers upload input files, download reports and files including their status, filter reports using URI parameters, and retrieve customer service metrics task details.</p>
 *
 * The version of the OpenAPI document: v1.3.1
 * @generated Generated by: https://openapi-generator.tech
 * Generator version: 7.25.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace eBay\Sell\Feed\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * StatusReasonEnumTest Class Doc Comment
 *
 * @description The enumeration value that indicates the reason the schedule template is &lt;code&gt;INACTIVE&lt;/code&gt;. | - **SCHEDULE_END_DATE_REACHED**: The active period for the schedule template has expired. Use the getScheduleTemplates method to find available active templates. - **DISABLED_TEMPLATE**: The template was disabled. Use the getScheduleTemplates method to find available active templates.
 * @package     eBay\Sell\Feed
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class StatusReasonEnumTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "StatusReasonEnum"
     */
    public function testStatusReasonEnum()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
